qpip: add missing self in enableMiniTV
Fixes the following error when exiting plugin:
File "/usr/lib/enigma2/python/Plugins/SystemPlugins/QPIP/qpip.py", line 973, in enableMiniTV
    open(ENABLE_LCDTV_PROCPATH, "w").write(oldLcdLiveTVEnable)
NameError: global name 'oldLcdLiveTVEnable' is not defined